# Generated by Django 5.2.4 on 2025-10-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_menu_name_alter_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(blank=True, db_column='type', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID restoran dari file sumber (resto_id)', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords from file', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu_list',
            field=models.TextField(blank=True, help_text="Raw 'list menu' string from file", null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='review_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
