# Generated by Django 5.2.4 on 2025-10-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_city_restaurant_cuisine_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(blank=True, default='media/resto_photos/plataran.jpg', null=True, upload_to='resto_photos/'),
        ),
    ]
