# Generated by Django 5.2.4 on 2025-10-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_alter_restaurant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(blank=True, default='resto_photos/default.jpeg', null=True, upload_to='resto_photos/'),
        ),
    ]
